'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

import { formatDate, formatStatus } from '../../lib/formatting/display';
import { lostPetDetailRoute, routes } from '../../lib/routes';
import { useAuth } from '../auth/use-auth';
import { WorkspaceState } from '../sightings/my-reports';
import { getMatch, type MatchResult } from './matches-api';

export function MatchDetail({ id }: { id: string }) {
  const auth = useAuth(); const [item,setItem]=useState<MatchResult|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  useEffect(() => { let active=true; void getMatch(auth.authenticatedRequest,id).then((result)=>{if(active)setItem(result)}).catch(()=>{if(active)setError('This match is unavailable or you do not have access.')}).finally(()=>{if(active)setLoading(false)}); return()=>{active=false}; },[auth.authenticatedRequest,id]);
  if (loading) return <div className="page-container"><WorkspaceState loading title="Loading match details…" /></div>; if (error || !item) return <div className="page-container"><WorkspaceState title="Match unavailable" description={error || 'This match could not be found.'} action={<Link className="primary-action" href={routes.matches}>Back to matches</Link>} /></div>;
  return <div className="page-container match-detail-page"><Link className="back-link" href={routes.matches}>← Back to matches</Link><header className="page-heading"><div><span className="eyebrow">Match review</span><h1>{item.lostPet.name} and a {formatStatus(item.sighting.species).toLowerCase()} sighting</h1><p>Compare timing, traits, and approximate distance without exposing private pins.</p></div><div className={`score-disc score-${item.level.toLowerCase()}`}><strong>{item.score}</strong><span>{formatStatus(item.level)}</span></div></header><section className="comparison-grid"><article className="detail-card"><span className="eyebrow">Lost pet</span><h2>{item.lostPet.name}</h2><p>Owner-accessible lost-pet post. Exact last-seen location remains hidden here.</p><Link className="secondary-action" href={lostPetDetailRoute(item.lostPet.id)}>Public pet details</Link></article><article className="detail-card"><span className="eyebrow">Evidence</span><dl className="detail-list"><div><dt>Review status</dt><dd>{formatStatus(item.reviewStatus)}</dd></div><div><dt>Matched</dt><dd>{formatDate(item.matchedAt)}</dd></div><div><dt>Distance</dt><dd>{item.distanceMeters === null ? 'Unavailable' : `${Math.round(item.distanceMeters).toLocaleString()} m approximate`}</dd></div><div><dt>Public area</dt><dd>Approximate area within {item.sighting.publicRadiusMeters.toLocaleString()} m</dd></div></dl></article><article className="detail-card"><span className="eyebrow">Sighting</span><h2>{formatStatus(item.sighting.species)} sighting</h2><dl className="detail-list"><div><dt>Condition</dt><dd>{formatStatus(item.sighting.condition)}</dd></div><div><dt>Seen</dt><dd>{formatDate(item.sighting.seenAt)}</dd></div></dl></article></section><section className="reason-panel"><h2>Why PetRadar matched these records</h2>{item.reasons.length ? <ul>{item.reasons.map((reason)=><li key={reason}>{reason}</li>)}</ul> : <p>No match reasons were returned.</p>}{item.rejectionReason ? <div className="feedback feedback-error">Review note: {item.rejectionReason}</div> : null}</section><aside className="privacy-note"><strong>No moderation controls</strong><span>This user-facing detail is read-only. ADMIN accounts see the same experience as other users here.</span></aside></div>;
}
